// BBL Pitcher Report Data — extracted from v4 통합 리포트 DOCX files
// Display order: 홍주환 → 정원진 → 김주원 → 권준서
window.BBL_PITCHERS = [
  {
    id: 'hong',
    name: '홍주환',
    nameEn: 'Hong Ju-hwan',
    video: 'assets/hong.mp4',
    velocity: 137.9,
    velocityAvg: 135.0,
    archetype: '하체 파워 주도형',
    archetypeEn: 'Power-dominant (mid strength)',
    tags: ['reactive+'],
    coreIssue: '모든 구간 기준 충족 · 뚜렷한 약점 없음',
    coreIssueEn: 'No bottleneck — maintain current balance',
    severity: 'NONE',
    date: '2026-04-24',
    physical: {
      weightKg: 75.0,
      heightCm: 170,
      cmjPower: { cmj: 56.9, sj: 47.0, cmjAbs: 4268, sjAbs: 3525, band: 'high' },
      maxStrength: { abs: 2092, perKg: 27.9, band: 'mid' },
      reactive: { cmj: 0.67, sj: 0.99, band: 'high' },
      ssc: { value: 1.08, band: 'mid' },
      release: { value: 54.7, band: 'mid' },
    },
    radar: [
      { key: 'cmj',   label: '폭발력',     sub: '하체 폭발력',    value: 56.9, display: '56.9',  lo: 40, hi: 50 },
      { key: 'sj',    label: '순수파워',   sub: '정지→폭발',    value: 47.0, display: '47.0',  lo: 38, hi: 50 },
      { key: 'str',   label: '버티는 힘',  sub: '최대 근력',    value: 27.9, display: '27.9',  lo: 25, hi: 35 },
      { key: 'rsi',   label: '빠른 반동',  sub: '순간 반응', value: 0.67, display: '0.67',  lo: 0.3, hi: 0.55 },
      { key: 'eur',   label: '반동 활용',  sub: '탄성 에너지',     value: 1.08, display: '1.08',  lo: 0.95, hi: 1.10 },
      { key: 'grip',  label: '손목 힘',    sub: '릴리스 안정',      value: 54.7, display: '54.7',  lo: 50, hi: 65 },
    ],
    sequence: {
      pelvisMs: 0, trunkMs: 41, armMs: 92,
      g1: 41, g2: 51,
      comment: '· 전 구간 이상 타이밍 범위 · 교과서적 시퀀스',
    },
    angular: {
      pelvis: 605, trunk: 805, arm: 1505,
      pelvisBand: 'mid', trunkBand: 'mid', armBand: 'mid',
      gainPT: 1.33, gainTA: 1.87,
      comment: '· 3개 분절 전부 기준 범위 · 밸런스 잡힌 회전 속도',
    },
    energy: {
      etiPT: 6.44, etiTA: 1.04, leakPct: 0,
      comment: '· 몸통→상완 에너지 전달 효율 1.04 · 누수 0% · 4명 중 최고 · lag 51 ms와 layback 187°가 모두 이상적 범위 · 흉추 가동성·분절 타이밍 모두 우수 · 현재 상태 유지하며 절대 근력 보강 시 추가 상승 여력',
    },
    command: {
      strikePct: 61.5, plateSdCm: 18.1, grade: 'B',
      breakdown: { leak: 0.0, layback: 3.1, eti: 3.4 },
      note: '· 누수 0% + layback 187°(정상) + ETI 1.04 → 안정적 메카닉 → 일관성 우수 추정',
      isDemo: true,
    },
    layback: { deg: 187.1, band: 'high', note: '· 프로 범위 180°+ 도달 · 가속 거리 충분' },
    strengths: [
      { title: '하체 단위파워 우수', detail: '· CMJ 단위파워 56.9 W/kg · 기준 상위' },
      { title: '반응·폭발성 (RSI) 우수', detail: '· CMJ RSI-mod 0.67 m/s · 기준 상위' },
      { title: '몸통→상완 에너지 전달 우수', detail: '· ETI 1.04 · 기준 상위' },
    ],
    weaknesses: [
      { title: '전 영역 기준 충족 · 약점 없음', detail: '· 현재 수준을 유지하며 절대 근력 보강 시 추가 상승 여력' },
    ],
    flags: [],
    training: [
      { cat: '근력', title: '근력 보강 (단위파워 유지)', weeks: '6–8주',
        rationale: '· 단위파워 이미 우수 · 절대 근력 증가 시 파워 총량 동반 상승 · 혼자서도 덤벨·자중 기반으로 진행 가능',
        drills: [
          '고블릿 스쿼트 (덤벨 1개) 4세트 × 6–8회 · 주 2회',
          '싱글 레그 루마니안 데드리프트 (덤벨) 3세트 × 8회 · 엉덩이-햄스트링 타깃',
          '스텝업 (의자·벤치) 3세트 × 10회 · 좌우 교대',
          '푸시업 변형 (일반·다이아몬드·디클라인) 4세트 × 15회',
          '셀프 체크: 각 세트 후 스마트폰 영상으로 자세 확인 · 무릎 안쪽 무너짐/허리 둥글림 없는지',
        ] },
    ],
  },
  {
    id: 'jeong',
    name: '정원진',
    nameEn: 'Jeong Won-jin',
    video: 'assets/jeong.mp4',
    velocity: 133.0,
    velocityAvg: 131.2,
    archetype: '파워 개발 필요형',
    archetypeEn: 'Power-deficit (strength untested)',
    tags: ['reactive-'],
    coreIssue: '몸통→상완 에너지 누수',
    coreIssueEn: 'Trunk → Arm energy transfer inefficiency',
    severity: 'HIGH',
    date: '2026-04-24',
    physical: {
      weightKg: 79.0,
      heightCm: 181,
      cmjPower: { cmj: 48.3, sj: 29.1, cmjAbs: 3816, sjAbs: 2299, band: 'low' },
      maxStrength: { abs: null, perKg: null, band: 'na' },
      reactive: { cmj: 0.49, sj: 0.27, band: 'low' },
      ssc: { value: 1.09, band: 'mid' },
      release: { value: 50.0, band: 'mid' },
    },
    radar: [
      { key: 'cmj',   label: '폭발력',     sub: '하체 폭발력',    value: 48.3, display: '48.3',  lo: 40, hi: 50 },
      { key: 'sj',    label: '순수파워',   sub: '정지→폭발',    value: 29.1, display: '29.1',  lo: 38, hi: 50 },
      { key: 'str',   label: '버티는 힘',  sub: '최대 근력',    value: null, display: 'N/A',   lo: 25, hi: 35 },
      { key: 'rsi',   label: '빠른 반동',  sub: '순간 반응', value: 0.27, display: '0.27',  lo: 0.3, hi: 0.55 },
      { key: 'eur',   label: '반동 활용',  sub: '탄성 에너지',     value: 1.09, display: '1.09',  lo: 0.95, hi: 1.10 },
      { key: 'grip',  label: '손목 힘',    sub: '릴리스 안정',      value: 50.0, display: '50.0',  lo: 50, hi: 65 },
    ],
    sequence: {
      pelvisMs: 0, trunkMs: 42, armMs: 80,
      g1: 42, g2: 38,
      comment: '· 전 구간 이상 타이밍 범위 · 교과서적 시퀀스',
    },
    angular: {
      pelvis: 610, trunk: 835, arm: 1478,
      pelvisBand: 'mid', trunkBand: 'mid', armBand: 'mid',
      gainPT: 1.37, gainTA: 1.77,
      comment: '· 3개 분절 전부 기준 범위 · 밸런스 잡힌 회전 속도',
    },
    energy: {
      etiPT: 7.06, etiTA: 0.77, leakPct: 22,
      comment: '· 몸통→상완 에너지 손실 약 22% · 핵심 원인 두 가지 · ① 몸통→상완 lag 38 ms로 짧음 (정상 40–60 ms) · ② 어깨 외회전(layback) 169° · 프로 기준 180°+ 미달 → 상완 가속 거리 부족 · 흉추 회전 가동성 + lag 의도적 늘리기 + RSI 보강(SSC 활용 ↑) 필요',
    },
    command: {
      strikePct: 49.5, plateSdCm: 23.7, grade: 'C',
      breakdown: { leak: -6.6, layback: 2.6, eti: -1.4 },
      note: '· 누수 22% + layback 169°(부족) → release point 변동 가능성 → 제구 기복 추정',
      isDemo: true,
    },
    layback: { deg: 169.2, band: 'mid', note: '· 프로 범위 160°–180° 내' },
    strengths: [
      { title: '신장성 활용 (SSC) 정상', detail: '· EUR 1.09 · SSC 활용 정상 범위' },
    ],
    weaknesses: [
      { title: '몸통→상완 에너지 누수', detail: '· ETI trunk→arm 0.77 · 기준 0.85 미만' },
      { title: '하체 단위파워 기준 미만', detail: '· SJ 단위파워 29.1 W/kg' },
      { title: '반응·폭발성 (RSI) 기준 미만', detail: '· SJ RSI-mod 0.27 m/s' },
    ],
    flags: [
      { severity: 'HIGH', title: '몸통→상완 에너지 누수',
        evidence: ['ETI trunk→arm 0.77 · 기준 0.85 미만'],
        implication: '· 몸통→상완 전달 손실 · lag drill 필요 · 흉추 회전 가동성 확보 · 분절 간 타이밍 재조정' },
    ],
    training: [
      { cat: '메카닉', title: '몸통→상완 에너지 전달 개선 (셀프)', weeks: '4–6주',
        rationale: '· ETI trunk→arm 기준(0.85) 미만 · 몸통 운동량 상완 전달 부족 · 혼자 매일 10분 루틴',
        drills: [
          'Connection ball 드릴 대체: 수건 두 개를 말아 겨드랑이에 끼우고 쉐도우 투구 30회 · 팔-몸통 분리감',
          'Lag 드릴: 수건 잡고 투구 동작 20회 · 수건이 늦게 따라오는 감각',
          '흉추 회전 모빌리티: Open Book 자세 좌우 10회 × 2세트 · 바닥에서 혼자',
          '거울 쉐도우: 거울 앞 투구 동작 15회 · 팔이 몸통보다 먼저 돌지 않는지 확인',
          '셀프 체크: 측면 셀카 영상으로 골반-어깨 분리각 30–45° 유지 여부',
        ] },
      { cat: '파워', title: '하체 파워 개발 (자중·점프)', weeks: '6–8주',
        rationale: '· 하체 단위파워 기준 미만 · 장비 없이 운동장/집에서 가능한 점프·플라이오 위주',
        drills: [
          '박스 점프 (계단·튼튼한 벤치 30–40cm) 3세트 × 5회 · 주 2회 · 충분한 휴식',
          '브로드 점프 (제자리멀리뛰기) 3세트 × 5회 · 착지 안정 우선',
          '점프 스쿼트 (자중) 4세트 × 6회 · 폭발적 상승',
          '측방 바운드 (좌우 점프) 3세트 × 8회 · 투구 하체 힘 방향 특화',
          '셀프 체크: 거리/높이를 매주 기록 · 10% 이내 편차면 일관성 OK',
        ] },
    ],
  },
  {
    id: 'kim',
    name: '김주원',
    nameEn: 'Kim Ju-won',
    video: 'assets/kim.mp4',
    velocity: 145.1,
    velocityAvg: 140.9,
    archetype: '재능형 · 능력 외 투구',
    archetypeEn: 'Skill-Outperforming · Talent-Driven',
    tags: ['skill-outperforming', 'injury-risk-high', 'high-upside'],
    coreIssue: '측정 데이터 대비 +13 km/h · 재능 위에 던지는 케이스 · 부상 위험 ↑ 보강 시 잠재력 큼',
    coreIssueEn: 'Throwing above measured capacity · injury risk + huge upside',
    severity: 'HIGH',
    date: '2026-04-24',
    physical: {
      weightKg: 85.0,
      heightCm: null,
      cmjPower: { cmj: 37.7, sj: 43.7, cmjAbs: 3205, sjAbs: 3715, band: 'low' },
      maxStrength: { abs: 2525, perKg: 29.7, band: 'mid' },
      reactive: { cmj: 0.46, sj: 0.62, band: 'high' },
      ssc: { value: 1.18, band: 'high' },
      release: { value: 74.2, band: 'high' },
    },
    radar: [
      // axis, label, sub, value, low, high, displayValue
      { key: 'cmj',   label: '폭발력',     sub: '하체 폭발력',    value: 37.7, display: '37.7',  lo: 40, hi: 50 },
      { key: 'sj',    label: '순수파워',   sub: '정지→폭발',    value: 43.7, display: '43.7',  lo: 38, hi: 50 },
      { key: 'str',   label: '버티는 힘',  sub: '최대 근력',    value: 29.7, display: '29.7',  lo: 25, hi: 35 },
      { key: 'rsi',   label: '빠른 반동',  sub: '순간 반응', value: 0.46, display: '0.46',  lo: 0.3, hi: 0.55 },
      { key: 'eur',   label: '반동 활용',  sub: '탄성 에너지',     value: 1.18, display: '1.18',  lo: 0.95, hi: 1.10 },
      { key: 'grip',  label: '손목 힘',    sub: '릴리스 안정',      value: 74.2, display: '74.2',  lo: 50, hi: 65 },
    ],
    sequence: {
      pelvisMs: 0, trunkMs: 51, armMs: 111,
      g1: 51, g2: 59,
      comment: '· 골반→몸통 간격 느림 · 하체 회전 완성 前 몸통 개방 가능성',
    },
    angular: {
      pelvis: 569, trunk: 682, arm: 1383,
      pelvisBand: 'low', trunkBand: 'low', armBand: 'low',
      gainPT: 1.20, gainTA: 2.03,
      comment: '· 3개 분절 모두 기준 미만 · 분절별 가속 부족',
    },
    energy: {
      etiPT: 4.16, etiTA: 0.68, leakPct: 31,
      comment: '· 몸통→상완 에너지 손실 약 31% · 흥미로운 패턴 · lag 60 ms · layback 195°로 이상적 · 그러나 trunk peak 682°/s로 4명 중 가장 낮음 · 즉 "전달 효율" 문제가 아닌 "몸통 회전 자체"가 약함 · 이런 데이터에도 145 km/h 던지는 이유 (가설) · 절대 IMTP 2,525 N (4명 중 1위) + 악력 74 kg (4명 중 1위) + EUR 1.18 (SSC 활용 우수) · 분절 peak 외 손목·전완 폭발력 + 신경근 효율로 보완 추정 · 흉추 회전 파워·코어 회전력 보강이 ETI 회복 지렛대',
    },
    command: {
      strikePct: 44.7, plateSdCm: 26.0, grade: 'D',
      breakdown: { leak: -9.3, layback: 2.0, eti: -3.1 },
      note: '· 누수 31% + ETI 0.68 + 분절 peak 약함 → 보상 메커니즘 의존 → 일관성 저하 추정',
      isDemo: true,
    },
    layback: { deg: 194.8, band: 'high', note: '· 프로 범위 180°+ 도달 · 가속 거리 충분' },
    strengths: [
      { title: '반응·폭발성 (RSI) 우수', detail: '· SJ RSI-mod 0.62 m/s · 기준 상위' },
      { title: '신장성 활용 (SSC) 우수', detail: '· EUR 1.18 · SSC 활용 강함 · CMJ·SJ 격차 큼' },
      { title: '악력 우수', detail: '· 악력 74.2 kg · 기준 상위 · 전완·손목 용량 충분' },
    ],
    weaknesses: [
      { title: '몸통→상완 에너지 누수', detail: '· ETI trunk→arm 0.68 · 기준 0.85 미만' },
      { title: '하체 단위파워 기준 미만', detail: '· CMJ 단위파워 37.7 W/kg' },
    ],
    flags: [
      { severity: 'HIGH', title: '몸통→상완 에너지 누수',
        evidence: ['ETI trunk→arm 0.68 · 기준 0.85 미만'],
        implication: '· 몸통→상완 전달 손실 · lag drill 필요 · 흉추 회전 가동성 확보 · 분절 간 타이밍 재조정' },
    ],
    training: [
      { cat: '메카닉', title: '몸통→상완 에너지 전달 개선 (셀프)', weeks: '4–6주',
        rationale: '· ETI trunk→arm 기준(0.85) 미만 · 분절 타이밍·흉추 가동성 핵심 축 · 매일 10분 혼자 수행',
        drills: [
          '수건 말아 겨드랑이 끼기 + 쉐도우 투구 30회 · 팔-몸통 분리 감각 형성',
          'Lag 드릴: 수건 끝 잡고 투구 20회 · 수건이 늦게 따라오는 느낌',
          'Open Book 흉추 모빌리티: 옆으로 누워 팔 여닫기 좌우 각 10회 × 2세트',
          '폼롤러 흉추 신전: 10회 × 2세트 (폼롤러 없으면 수건 말아서 대체)',
          '셀프 체크: 측면 셀카로 골반-어깨 분리각 유지(30–45°, 0.05초 이상) 확인',
        ] },
      { cat: '파워', title: '파워 변환 (점프·플라이오 중심)', weeks: '6–8주',
        rationale: '· 절대 근력 양호 · 폭발적 발현력 부족 · 혼자서 가능한 점프·탄성 드릴로 RSI 개선',
        drills: [
          '뎁스 점프 (낮은 계단 30cm) 3세트 × 5회 · 땅 닿자마자 바로 점프',
          '회전 메디볼 던지기 (3–5kg) 좌우 각 4세트 × 6회 · 벽 대고 가능',
          '스플릿 점프 스쿼트 (자중·덤벨 선택) 3세트 × 6회 좌우 · 파워 변환 훈련',
          '브로드 점프 3세트 × 5회 · 매주 거리 기록',
          '셀프 체크: 점프 높이/거리가 4주 내 5–10% 증가하면 파워 변환 진행 중',
        ] },
    ],
  },
  {
    id: 'kwon',
    name: '권준서',
    nameEn: 'Kwon Jun-seo',
    video: 'assets/kwon.mp4',
    velocity: 122.7,
    velocityAvg: 121.1,
    archetype: '탄력 중심형',
    archetypeEn: 'Lightweight / Elastic',
    tags: ['reactive+'],
    coreIssue: '· 엔진 총량 부족 · 몸통→상완 전달 저하',
    coreIssueEn: 'Low engine size + Trunk → Arm inefficiency',
    severity: 'HIGH',
    date: '2026-04-24',
    physical: {
      weightKg: 65.4,
      heightCm: 181,
      cmjPower: { cmj: 56.7, sj: 57.5, cmjAbs: 3708, sjAbs: 3762, band: 'high' },
      maxStrength: { abs: 1765, perKg: 27.0, band: 'mid' },
      reactive: { cmj: 0.48, sj: 0.97, band: 'high' },
      ssc: { value: 1.10, band: 'mid' },
      release: { value: 49.1, band: 'mid' },
    },
    radar: [
      { key: 'cmj',   label: '폭발력',     sub: '하체 폭발력',    value: 56.7, display: '56.7',  lo: 40, hi: 50 },
      { key: 'sj',    label: '순수파워',   sub: '정지→폭발',    value: 57.5, display: '57.5',  lo: 38, hi: 50 },
      { key: 'str',   label: '버티는 힘',  sub: '최대 근력',    value: 27.0, display: '27.0',  lo: 25, hi: 35 },
      { key: 'rsi',   label: '빠른 반동',  sub: '순간 반응', value: 0.97, display: '0.97',  lo: 0.3, hi: 0.55 },
      { key: 'eur',   label: '반동 활용',  sub: '탄성 에너지',     value: 1.10, display: '1.10',  lo: 0.95, hi: 1.10 },
      { key: 'grip',  label: '손목 힘',    sub: '릴리스 안정',      value: 49.1, display: '49.1',  lo: 50, hi: 65 },
    ],
    sequence: {
      pelvisMs: 0, trunkMs: 31, armMs: 77,
      g1: 31, g2: 46,
      comment: '· 전 구간 이상 타이밍 범위 · 교과서적 시퀀스',
    },
    angular: {
      pelvis: 540, trunk: 929, arm: 1486,
      pelvisBand: 'low', trunkBand: 'high', armBand: 'mid',
      gainPT: 1.72, gainTA: 1.60,
      comment: '· 몸통 강점 · 골반 기준 미만 · 분절 간 가속 패턴 불균형',
    },
    energy: {
      etiPT: 6.44, etiTA: 0.60, leakPct: 39,
      comment: '· 몸통→상완 에너지 손실 약 39% (4명 중 최대) · trunk peak 929°/s로 매우 빠름 (4명 중 1위) · 그러나 arm peak 1486°/s로 비슷한 수준 · 즉 강력한 몸통 회전이 상완으로 거의 전달 안 됨 · 어깨 stabilizer 약함·timing 동기화 미흡·overstride 가능성 · 메카닉 보강이 구속 +14 km/h 잠재력 회복의 핵심',
    },
    command: {
      strikePct: 42.0, plateSdCm: 27.3, grade: 'D',
      breakdown: { leak: -11.7, layback: 3.2, eti: -4.5 },
      note: '· 누수 39%(최대) + ETI 0.60 + trunk-arm 동기화 미흡 → 일관성 가장 약할 가능성',
      isDemo: true,
    },
    layback: { deg: 186.3, band: 'high', note: '· 프로 범위 180°+ 도달 · 가속 거리 충분' },
    strengths: [
      { title: '하체 단위파워 우수', detail: '· CMJ 단위파워 56.7 W/kg · 기준 상위' },
      { title: '반응·폭발성 (RSI) 우수', detail: '· SJ RSI-mod 0.97 m/s · 기준 상위' },
      { title: '어깨 외회전 가동범위 우수', detail: '· Max Layback 186° · 기준 상위' },
    ],
    weaknesses: [
      { title: '몸통→상완 에너지 누수', detail: '· ETI trunk→arm 0.60 · 기준 0.85 미만' },
      { title: '엔진 총량 부족', detail: '· 단위파워 양호 · 절대 용량 작음 (1765 N / 65.4 kg)' },
    ],
    flags: [
      { severity: 'MEDIUM', title: '엔진 총량 부족 · 단위파워 양호 · 절대 용량 작음',
        evidence: ['절대 근력 추정치 1765 N (IMTP_F) · Low 범위', '체중 65.4 kg', 'CMJ 단위파워 56.7 W/kg · High'],
        implication: '· 탄력·반응성 양호 · 근력·체중 총량 작음 · 구속 천장 제한 · 중량 복합운동 중심 절대 근력·체중 증가 블록 우선' },
      { severity: 'HIGH', title: '몸통→상완 에너지 누수',
        evidence: ['ETI trunk→arm 0.60 · 기준 0.85 미만'],
        implication: '· 몸통→상완 전달 손실 · lag drill 필요 · 흉추 회전 가동성 · 분절 간 타이밍 재조정' },
    ],
    training: [
      { cat: '메카닉', title: '몸통→상완 에너지 전달 개선 (셀프)', weeks: '4–6주',
        rationale: '· ETI trunk→arm 기준(0.85) 미만 · 몸통 운동량 상완 전달 부족 · 매일 10분 루틴',
        drills: [
          '수건 겨드랑이 끼기 + 쉐도우 투구 30회 · 팔-몸통 연결 감각',
          'Lag 드릴: 수건 휘두르기 20회 · 팔 지연 타이밍',
          'Open Book 흉추 회전 좌우 각 10회 × 2세트',
          '폼롤러 흉추 신전 10회 × 2세트 · 폼롤러 없으면 타월 말아 사용',
          '셀프 체크: 측면 영상으로 분절 타이밍(골반→몸통→팔 순서) 확인',
        ] },
      { cat: '근력', title: '근력·체중 증가 블록 (홈·자중 중심)', weeks: '8–12주',
        rationale: '· 단위체중 파워 양호 · 절대 근력/체중 작음 · 혼자서 식단과 자중·덤벨 훈련 병행',
        drills: [
          '고블릿 스쿼트 (덤벨·배낭에 짐 넣어 대체 가능) 4세트 × 8–10회 · 주 2회',
          '불가리안 스플릿 스쿼트 3세트 × 8회 좌우 · 하체 근비대',
          '푸시업 (가중 옵션: 배낭) 4세트 × 최대 반복',
          '풀업/로우: 철봉 풀업 or 수건 후면 당김 (철봉 없으면 인버티드 로우)',
          '식단: 하루 단백질 체중 1kg당 1.6–2.0g · 0.25–0.5 kg/주 체중 증가 목표',
          '셀프 체크: 매주 같은 요일·시간 체중 측정 · 사진 기록(정면·측면)',
        ] },
    ],
  },
];

// Professional reference ranges
window.BBL_REF = {
  pelvis:  { low: 580, high: 640 },
  trunk:   { low: 800, high: 900 },
  arm:     { low: 1450, high: 1600 },
  layback: { low: 160, high: 180 },
  etiTA:   { leakBelow: 0.85, ideal: 1.0 },
};
